### ISSUE TITLE
Best way to modify InputView?

### ISSUE THREAD

**Issue by airandfingers** [AmpersandJS/ampersand-input-view#33]
I'm trying out Ampersand by creating a simple chat page by modifying the sample app.

For this chat page, I have a message input field that I want to behave like InputView, but with two changes:

* I don't want the field's validity to be checked on blur.
* I want reset to set shouldValidate to false.

Right now I'm simply doing:

    var InputView = require('ampersand-input-view');
    // modify InputView to behave as we want it to
    InputView.prototype.handleBlur = function() {};
    InputView.prototype.reset = function() {
        this.setValue('');
        this.shouldValidate = false;
    }

Is there a better way? I tried this with no success:

    ExtendedInputView = InputView.extend({
        handleBlur: ...
        reset: ...
    });

I'd also like to give the input an "autofocus: true" attribute, but the only ways I know how to do that would be to completely override the template, or wait until the input has been rendered, then do something like `input_view.get('.form-input').setAttribute('autofocus', true);`

One thing I was able to find out was how to override a derived property:

    ExtendedInputView = InputView.extend({
        derived: {
            validityClass: {
                deps: ['valid', 'validClass', 'invalidClass', 'shouldValidate'],
                fn: function () {
                    if (!this.shouldValidate) {
                        return '';
                    } else {
                        return this.valid ? this.validClass : this.invalidClass;
                    }
                }
            }
        }
    });

At some point, it makes more sense to simply create my own version of InputView; I'd just like to know how much of what I want is possible without doing so.

**Comment by wraithgar** [comment]
Overriding the template is the preferred method of changing what is rendered.

Validation won't run if the field isn't required and you don't run tests.  I *think* setting `required: false` will achieve the behavior you want.

**Comment by cdaringe** [comment]
we no longer validate onblur, so that's taken care of.  this is likely to prevent validation from popping up from just tabbing thru.  the template is the place likely to drop your auto-focus attr, just as wraithgar suggested.  of course, your post-render method can work too!  it looks like setting `shouldValidate` to false on `reset()` has already made it into the repo as shown [here](https://github.com/AmpersandJS/ampersand-input-view/blob/master/ampersand-input-view.js#L213) then [here](https://github.com/AmpersandJS/ampersand-input-view/blob/master/ampersand-input-view.js#L142)

with that said, sounds like you're good to go!  of course, follow back up if we missed anything
