### ISSUE TITLE
Allow labels to be explicitly associated with inputs (using for attribute)

### ISSUE THREAD

**Issue by clarehyam** [AmpersandJS/ampersand-input-view#54]
Currently the labels supplied in the default template are implicitly associated with the inputs (using nesting). 

```<label>Name<input type="text" /></label>```

It would be awesome to be able to associate them explicitly with a "for" attribute that references the id of the input through an option or by default. They are a little more robust than using nesting (and easier to style - when doing rtl layouts, needing to hide one without the other etc) and preferred in terms of accessibility.
 
```<label for="InputId">Name</label>
    <input type="text" id="InputId" />```

I know this should be easy enough to achieve although I wasn't sure whether there would be a preference on how the id property should be generated for this or whether there would ever be a need to pass them in? I'm wary of them having to be unique.

**Comment by wraithgar** [comment]
This would be a great addition, if we could get the api right for it.  It would need to be something off by default and enabled via config.

Let's start small w/ lots of assumptions and work inward from there, being cautious not to prematurely optimize:

At its simplest this could be a config item `for` that's set to true, and then in `render` the `label` and `input` tags are found and applied a random id/for attribute, with the randomization being skipped if the input already has an id in which case that id would be set to the label's `for` field?

Instead of, or maybe even in as an alternative to the boolean you could pass in an array of [labelTagSelector, inputTagSelector] or object {label: labelTagSelector, input: inputTagSelector} if for some reason you needed those altered?

@clarehyam is this anywhere close to what you were thinking? I'd love to hear what your expectations were for how this would look to the end user.

As far as generating ids, node-uuid is [pretty tiny](https://github.com/broofa/node-uuid)

**Comment by clarehyam** [comment]
@wraithgar This sounds perfect, Apologies I've been super busy this week but I really appreciated your thorough reply :) 

The boolean sounds good, I guess in this case we would have to go off of a selector for the label as the 'label' hook isn't necessarily on the label element so I think the being able to optionally pass in this and/or the input selector would be wise (makes it bit easier if you do end up using a select box instead of an input in future etc).

**Comment by gonsfx** [comment]
Why don't you just overwrite the `template` property and generate a unique id using `amp-unique-id`?
I'm not sure if this has to be added into the module itself.
